os:
  edit: "~/dots/scripts/nvim-tmux-edit.sh {{filename}}"
  editAtLine: "~/dots/scripts/nvim-tmux-edit.sh +{{line}} -- {{filename}}"
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      printf "\033Ptmux;\033\033]52;c;$(printf {{text}} | base64 -w 0)\a\033\\" > /dev/tty
    else
      printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty
    fi
keybinding:
  commits:
    moveDownCommit: <c-d>
    moveUpCommit: <c-u>
gui:
  nerdFontsVersion: "3"
